### PR TITLE
added 'Create ExReg'

### PR DESCRIPTION
**Pull request by Bestyan**
Dear fellow team member,
please integrate our user story implementation.

### CODE REVIEW

**Comment by schmolli** [comment]
You pushed a new version during review. Please, write a message before force-pushing next time.

**Comment by Bestyan** [comment]
I'm sorry about that. The PR had merge conflicts after "improve moduleCreate" was merged, so I didn't think you'd even review it at that point.

**Comment by schmolli** [comment]
OK, there are still some bugs:
a) Create another semester, add some modules to both. Click on Delete Semester 1 -> Semester 2 is deleted.
b) The placeholder for drag and drop disappears after one d&d operation. 

Please improve your code and update your pull request afterwards.

**Comment by Bestyan** [comment]
In our opinion, both features are working as intended. Maybe we should discuss it at the next meeting.

**Comment by schmolli** [comment]
OK, we will see, perhaps you are right. Please, avoid imports with * character in the future.

**Pull request merged**
