### PR TITLE
"update spring boot version 2.3.0 and java version 11"

### PR DESCRIPTION
**Pull request by DennisGemeinhardt1993**

### CODE REVIEW

**Comment by schmolli** [comment]
Hi Dennis,
1) The indentation of pom.xml looks strange, especially in the area of the dependencies. Did you use tabs or spaces? Please use spaces.
2) Probably, you tested the app locally. Travis was fine with the build, too. Can you please have a looks at the documentations if we can use openjdk14 as a base for Cloudfoundry Apps in the IBM Cloud.

**Comment by TimMeinhof** [comment]
> Hi Dennis,
> 
> 1. The indentation of pom.xml looks strange, especially in the area of the dependencies. Did you use tabs or spaces? Please use spaces.
> 2. Probably, you tested the app locally. Travis was fine with the build, too. Can you please have a looks at the documentations if we can use openjdk14 as a base for Cloudfoundry Apps in the IBM Cloud.

After we upgraded Springboot to the latest version, I thought it would make sense to do this with Java too and according to the IBM documentation OpenJDK14 is supported in the cloud since March 2020. We can also take OpenJDK11, which do you prefer more? @schmolli

**Comment by schmolli** [comment]
> > Hi Dennis,
> > 
> > 1. The indentation of pom.xml looks strange, especially in the area of the dependencies. Did you use tabs or spaces? Please use spaces.
> > 2. Probably, you tested the app locally. Travis was fine with the build, too. Can you please have a looks at the documentations if we can use openjdk14 as a base for Cloudfoundry Apps in the IBM Cloud.
> 
> After we upgraded Springboot to the latest version, I thought it would make sense to do this with Java too and according to the IBM documentation OpenJDK14 is supported in the cloud since March 2020. We can also take OpenJDK11, which do you prefer more? @schmolli

I prefer Java 11, since it is currently the LTS version. The LTS version changes every 3 years, I thinks that is OK for our project. 14 is too new, for certain tools. E.g. VS-Code does not support 14 at the moment.

**Comment by DennisGemeinhardt1993** [comment]
@schmolli We changed the Java version as requested.

**Comment by schmolli** [comment]
Hi, it seems as if the issue 47 https://github.com/turncodr/my-curriculum/issues/47 is related to the update of spring boot. So this PR should contain commits fixing the issue with the new spring boot version.

**Comment by schmolli** [comment]
Please, rebase your branch with upstream master!

**Pull request closed without merging**
